[package]
name = "shs"
version = "0.1.0"
authors = ["Nicholas Bishop <nicholasbishop@gmail.com>"]
edition = "2018"

[dependencies]
anyhow = "1.0"
log = "0.4"
fehler = "1.0"
serde = { version = "1.0", features = ["derive"] }